### ISSUE TITLE
Film descriptions are not particularly readable

### ISSUE THREAD

**Issue by sersorrel** [HackSoc/philmnight#27]
![image](https://user-images.githubusercontent.com/9433472/93785848-7891cf80-fc26-11ea-9ee6-552e1380445d.png)

This text is currently coloured by `body { color: var(--fg-color) }` which is almost black, even though the background is a gradient from black to transparent.

**Comment by dob9601** [comment]
Darn, I thought I had set this to be the same as the lighter background colour, it shall be rectified
