### ISSUE TITLE
Submission textbox doesn't look like a textbox

### ISSUE THREAD

**Issue by sersorrel** [HackSoc/philmnight#28]
![image](https://user-images.githubusercontent.com/9433472/93786209-f0f89080-fc26-11ea-8098-eb5a9cb0321a.png)

Using a `placeholder` might help, though strictly speaking this isn't how that's meant to be used:

![image](https://user-images.githubusercontent.com/9433472/93786252-feae1600-fc26-11ea-8727-9f295e4f02cc.png)

**Comment by dob9601** [comment]
Closed by 49f0ea405a492d81f573508915ec65e2ad65da42
